### ISSUE TITLE
Error when waiting for serverless stack to complete

### ISSUE THREAD

**Issue by maxotek** [aws/aws-extensions-for-dotnet-cli#125]
I am doing a `dotnet lambda deploy-serverless` and trying to figure out the minimum IAM permissions needed for the build server.

I get the following error when the `cloudformation:DescribeStacks` IAM permission was missing. Had to look into the code to understand what was missing.

```
Unknown error executing command: Object reference not set to an instance of an object.
[11:08:35][Step 4/4]    at Amazon.Lambda.Tools.Commands.DeployServerlessCommand.WaitStackToCompleteAsync(String stackName, DateTime mintimeStampForEvents) in C:\codebuild\tmp\output\src666071327\src\src\Amazon.Lambda.Tools\Commands\DeployServerlessCommand.cs:line 449
[11:08:35][Step 4/4]    at Amazon.Lambda.Tools.Commands.DeployServerlessCommand.PerformActionAsync() in C:\codebuild\tmp\output\src666071327\src\src\Amazon.Lambda.Tools\Commands\DeployServerlessCommand.cs:line 364
[11:08:35][Step 4/4]    at Amazon.Common.DotNetCli.Tools.Commands.BaseCommand`1.ExecuteAsync() in C:\codebuild\tmp\output\src666071327\src\src\Amazon.Common.DotNetCli.Tools\Commands\BaseCommand.cs:line 44
```

Perhaps this error should be thrown?

https://github.com/aws/aws-extensions-for-dotnet-cli/blob/6f5ce4420d1fee98b8e43ab984cbd925d874e281/src/Amazon.Lambda.Tools/Commands/DeployServerlessCommand.cs#L570

**Comment by ashishdhingra** [comment]
To mitigate the issue, one of the following options could be considered:
- Log the exception, if any in `GetExistingStackAsync()`.
- Pass the boolean parameter (default value false) to `GetExistingStackAsync()` to indicate whether to throw exception or not.
- As part of prerequisite, check could be executed if the account has `cloudformation:DescribeStacks` IAM policy attached.
