### ISSUE TITLE
lambda deploy ignores --skip-image-push when given --image-tag

### ISSUE THREAD

**Issue by CrescentFresh** [aws/aws-extensions-for-dotnet-cli#189]
## Description

When using the `--image-tag`  parameter combined with the `--skip-image-push` parameter,  the deploy-function command still attempts to first build and push the image up to ECR.

## Reproduction Steps

(Implied: I have already tagged and pushed my image to ECR)

```
dotnet lambda deploy-function my-function --image-tag 12345678.dkr.ecr.us-east-1.amazonaws.com/my-function-image:1.0 --skip-image-push
```

### Logs

```
Amazon Lambda Tools for .NET Core applications (5.1.4)
 Project Home: https://github.com/aws/aws-extensions-for-dotnet-cli, https://github.com/aws/aws-lambda-dotnet
 	
 Unknown error executing command: Failed to locate docker CLI executable. Make sure the docker CLI is installed in the environment PATH.
    at Amazon.Common.DotNetCli.Tools.DockerCLIWrapper..ctor(IToolLogger logger, String workingDirectory) in C:\codebuild\tmp\output\src933647099\src\src\Amazon.Common.DotNetCli.Tools\DockerCLIWrapper.cs:line 20
    at Amazon.Common.DotNetCli.Tools.Commands.BasePushDockerImageCommand`1.PerformActionAsync() in C:\codebuild\tmp\output\src933647099\src\src\Amazon.Common.DotNetCli.Tools\Commands\BasePushDockerImageCommand.cs:line 82
    at Amazon.Common.DotNetCli.Tools.Commands.BaseCommand`1.ExecuteAsync() in C:\codebuild\tmp\output\src933647099\src\src\Amazon.Common.DotNetCli.Tools\Commands\BaseCommand.cs:line 46
 ERROR: Job failed: exit code 1
```

### Environment
* OS Info: Debian
* Build Environment: Docker, base image that does not have docker cli (as I don't need it): mcr.microsoft.com/dotnet/sdk:5.0-buster-slim
* Targeted .NET Platform:  .NET Core 5.0

---

This is a :bug: bug-report

**Comment by CrescentFresh** [comment]
Looking at https://github.com/aws/aws-extensions-for-dotnet-cli/blob/master/src/Amazon.Lambda.Tools/Commands/DeployFunctionCommand.cs#L168 I see that if `--image-tag` is given at the command line the processing blindly attempts to push the image first:

```c#
if (packageType == Lambda.PackageType.Image)
{
    var pushResults = await PushLambdaImageAsync();

    if (!pushResults.Success)
    {
        if (pushResults.LastToolsException != null)
            throw pushResults.LastToolsException;

        return false;
    }

    ecrImageUri = pushResults.ImageUri;
}
```

It is unclear to me if the generic `--skip-image-push` is available to check at this point in the code.

**Comment by ashishdhingra** [comment]
> Looking at https://github.com/aws/aws-extensions-for-dotnet-cli/blob/master/src/Amazon.Lambda.Tools/Commands/DeployFunctionCommand.cs#L168 I see that if `--image-tag` is given at the command line the processing blindly attempts to push the image first:
> 
> ```cs
> if (packageType == Lambda.PackageType.Image)
> {
>     var pushResults = await PushLambdaImageAsync();
> 
>     if (!pushResults.Success)
>     {
>         if (pushResults.LastToolsException != null)
>             throw pushResults.LastToolsException;
> 
>         return false;
>     }
> 
>     ecrImageUri = pushResults.ImageUri;
> }
> ```
> 
> It is unclear to me if the generic `--skip-image-push` is available to check at this point in the code.

Hi @CrescentFresh,

Good afternoon.

After reviewing this issue, 
- There appears to be no support for `--skip-image-push` option for `lambda deploy-function` (refer [LambdaDefinedCommandOptions](https://github.com/aws/aws-extensions-for-dotnet-cli/blob/master/src/Amazon.Lambda.Tools/LambdaDefinedCommandOptions.cs)).
- The `--skip-image-push` is only supported in `Amazon.ECS.Tools` (`dotnet ecs`), refer [ECSDefinedCommandOptions](https://github.com/aws/aws-extensions-for-dotnet-cli/blob/01cd7391032bd0cebc7c85159bf60a0aa74e1510/src/Amazon.ECS.Tools/ECSDefinedCommandOptions.cs#L43).

Hence, this doesn't appear to be a bug. Kindly review.

Thanks,
Ashish
